### PR TITLE
fix: custom event endpoint was wrong

### PR DESCRIPTION
**Pull request by peterdeme**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
One is for [channel](https://github.com/GetStream/stream-chat-js/blob/master/src/channel.ts#L218) and the other is for [user](https://github.com/GetStream/stream-chat-js/blob/master/src/client.ts#L2802).

**Comment by ferhatelmas** [comment]
Our naming isn't very consistent `sendEvent` vs `sendCustomEvent`

**Comment by peterdeme** [comment]
@ferhatelmas the naming is consistent with the javascript library as far as I see:

- https://github.com/GetStream/stream-chat-php/blob/fix-custom-event/lib/GetStream/StreamChat/Client.php#L1131
- https://github.com/GetStream/stream-chat-php/blob/fix-custom-event/lib/GetStream/StreamChat/Channel.php#L97

**Comment by ferhatelmas** [comment]
> the naming is consistent with the javascript library

yes but not with others (go etc.)

**Comment by peterdeme** [comment]
Good notice. I renamed it to sendUserCustomEvent.

**Pull request closed without merging**
